### ISSUE TITLE
German BERT

### ISSUE THREAD

**Issue by malo1** [abotkit/abotkit#12]
## Feature Request
- I would like to use the program in German. Please add this feature

**Comment by maxlorenz** [comment]
We use [sentence-transformers](https://github.com/UKPLab/sentence-transformers#pretrained-models) in Python to detect the intent. See `botkit/core/transformer.py`. Currently, the model is hardcoded to be in English, maybe you have some luck with the [multilingual models](https://github.com/UKPLab/sentence-transformers#multilingual-models)?

We're very open for pull requests to dynamically choose the model on startup!

**Comment by fabianbormann** [comment]
@malo1 we use trello to track our issues and "German BERT" is already on our roadmap 👍for the next sprint
