### ISSUE TITLE
Enter does not work in UI

### ISSUE THREAD

**Issue by malo1** [abotkit/abotkit#14]
## Recreation
- I enter "Default Bot" in the "I have a bot" text field
## Expected
- I expected to go to the next page when hitting "Enter" after entering the bot name
## Observed
- I have to click on the button next to the text field, "Enter" does not work

**Comment by maxlorenz** [comment]
@fabianbormann seems like an UI issue ;)

**Comment by fabianbormann** [comment]
Oh no... I'm the "ui guy" :'D ... @malo1 thanks for testing ! I will fix that behavior soon 😊
