### ISSUE TITLE
Log queries of the handle endpoint in maeve

### ISSUE THREAD

**Issue by fabianbormann** [abotkit/abotkit#65]
As a customer I want to see the last or most important questions of the users so we need to log them to visualize them in near future.

**Comment by nmelche** [comment]
Rasa uses a tracker store in which all conversations are stored. Maybe we can adapt this concept to maeve and create a universal store for robert based and rasa based bots.

**Comment by fabianbormann** [comment]
done by abotkit/maeve@1e060cc
